sudo: true
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - npm run cover
after_success:
  - codecov
branches:
  only:
    - master